# Default Configuration for Plant Disease MobileNetV3 Pipeline

data:
  dataset_dir: "/kaggle/input/datasets/thnhvinhs/spmohanty-plantvillage-dataset/PlantVillage-Dataset/raw/color" # Adjust depending on Kaggle dataset path
  image_size: 224
  batch_size: 64
  num_workers: 4

model:
  num_classes: 38
  pretrained: true
  pretrained_path: "DEFAULT" # Indicates downloading from torchvision

training:
  epochs: 200
  learning_rate: 0.0001
  weight_decay: 0.0
  betas: [0.5, 0.99]
  early_stopping_patience: 20
  save_dir: "/checkpoints"

hpo:
  n_trials: 5
  lr_min: 1e-5
  lr_max: 1e-3
  weight_decay_min: 1e-6
  weight_decay_max: 1e-3
